### ISSUE TITLE
`base.py` defines `cmd_regwrite()` twice

### ISSUE THREAD

**Issue by Cabalist** [jamesbowman/gd2-asset#13]
Just noticed that `gs2-asset/base.py:GD2` defines `cmd_regwrite`  the second one is used but is that correct?

https://github.com/jamesbowman/gd2-asset/blob/93a7b7a853bc8459e1f3cbf47c8e426cf331f95f/gameduino2/base.py#L183-L188

**Comment by jamesbowman** [comment]
Thanks, removed the first one.
