### ISSUE TITLE
Add 'botchar' to font encoding

### ISSUE THREAD

**Issue by jamesbowman** [jamesbowman/gd2-asset#5]
'botchar' should specify the first character to encode. Default should be 32, as is current behavior.

http://gameduino2.proboards.com/thread/189/custom-font?page=1&scrollTo=1600

**Comment by MangyDogUK** [comment]
Ohhh this would be incredibly useful for my project too... But could you also add a characters used option.... for example.
*terrible sudo code*
gd2asset OCRstd.ttf , size=80, firstchar=47, lastchar=58 , charset ="N1234567890"

tbh if you have a charset listed you wouldnt need a topchar argument.

In Screen Editor you can set the chars used and the first char and it converts the assets throwing the rest out... N in this case was "/" as that was the char before 1 in ascii i think....

**Comment by jamesbowman** [comment]
OK, the command:

    gd2asset OCRstd.ttf,size=80,firstchar=47,lastchar=58,charset ="N1234567890"

encodes a font with the digits plus "N" for character code 47.
