### ISSUE TITLE
Changes for Mac support

### ISSUE THREAD

**Issue by ReeceWeb** [jamesbowman/gd2-asset#9]
I was able to get gd3asset working on current macOS by changing all instances of "import Image" to "from PIL import Image".  This allows the script to use the PIL that is distributed with Pillow.  I'm not sure if that would create problems for Linux/Windows users, but if not please consider pulling this into TOT.

**Comment by jamesbowman** [comment]
Yes, ```from PIL import Image``` is now used throughout.

Closing.
